/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.2.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Cell { 'value' : Value, 'name' : string }
export type CommentId = bigint;
export interface CommentInput {
  'x' : number,
  'y' : number,
  'text' : string,
  'author' : string,
}
export interface CommentView {
  'x' : number,
  'y' : number,
  'id' : CommentId,
  'tabId' : TabId,
  'createdAt' : Timestamp,
  'text' : string,
  'author' : string,
  'replies' : Array<ReplyView>,
}
export type Error = { 'FrontendOriginsNotConfigured' : null } |
  {
    'MixedSsoSources' : {
      'otherKeys' : Array<string>,
      'ssoKeys' : Array<string>,
    }
  } |
  { 'Stale' : { 'ageNs' : bigint } } |
  { 'MalformedCandid' : null } |
  { 'AmbiguousAttribute' : { 'field' : string, 'sources' : Array<string> } } |
  { 'NoAttributes' : null } |
  { 'UnknownNonce' : null } |
  { 'UntrustedSsoSource' : { 'domain' : string } } |
  { 'MissingField' : string } |
  { 'FrontendOriginMismatch' : { 'got' : string, 'expected' : Array<string> } };
export interface GeneratedRegionView {
  'x' : number,
  'y' : number,
  'id' : RegionId,
  'height' : number,
  'status' : RegionStatus,
  'tabId' : TabId,
  'createdAt' : Timestamp,
  'updatedAt' : Timestamp,
  'prompt' : string,
  'width' : number,
  'generatedHtml' : string,
}
export interface Point { 'x' : number, 'y' : number }
export interface PresenceInput {
  'displayName' : string,
  'color' : string,
  'activeTabId' : TabId,
  'cursorX' : number,
  'cursorY' : number,
  'activeTool' : string,
}
export interface PresenceView {
  'principal' : PrincipalText,
  'displayName' : string,
  'color' : string,
  'activeTabId' : TabId,
  'cursorX' : number,
  'cursorY' : number,
  'lastSeen' : Timestamp,
  'activeTool' : string,
}
export type PrincipalText = string;
export type ProjectId = bigint;
export interface ProjectView {
  'id' : ProjectId,
  'name' : string,
  'createdAt' : Timestamp,
  'updatedAt' : Timestamp,
}
export type RegionId = bigint;
export interface RegionInput {
  'x' : number,
  'y' : number,
  'height' : number,
  'prompt' : string,
  'width' : number,
}
export type RegionStatus = { 'pending' : null } |
  { 'done' : null } |
  { 'generating' : null } |
  { 'error' : null };
export interface RegionUpdate {
  'x' : [] | [number],
  'y' : [] | [number],
  'height' : [] | [number],
  'status' : [] | [RegionStatus],
  'prompt' : [] | [string],
  'width' : [] | [number],
  'generatedHtml' : [] | [string],
}
export interface RegionVersionView {
  'versionId' : bigint,
  'createdAt' : Timestamp,
  'prompt' : string,
  'regionId' : RegionId,
  'generatedHtml' : string,
}
export interface ReplyInput { 'text' : string, 'author' : string }
export interface ReplyView {
  'createdAt' : Timestamp,
  'text' : string,
  'author' : string,
}
export interface Result { 'hasMore' : boolean, 'rows' : Array<Array<Cell>> }
export type Result__1 = { 'ok' : null } |
  { 'err' : Error };
export type StrokeId = bigint;
export interface StrokeInput {
  'color' : string,
  'size' : number,
  'tool' : Tool,
  'points' : Array<Point>,
}
export interface StrokeView {
  'id' : StrokeId,
  'tabId' : TabId,
  'createdAt' : Timestamp,
  'color' : string,
  'size' : number,
  'tool' : Tool,
  'points' : Array<Point>,
}
export type TabId = bigint;
export interface TabView {
  'id' : TabId,
  'order' : bigint,
  'name' : string,
  'createdAt' : Timestamp,
  'updatedAt' : Timestamp,
  'projectId' : ProjectId,
}
export type TemplateId = bigint;
export interface TemplateView {
  'id' : TemplateId,
  'html' : string,
  'name' : string,
  'description' : string,
  'category' : string,
}
export type Timestamp = bigint;
export type Tool = { 'pen' : null } |
  { 'eraser' : null };
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export type Value = { 'int' : bigint } |
  { 'nat' : bigint } |
  { 'float' : number } |
  { 'bool' : boolean } |
  { 'null' : null } |
  { 'text' : string };
export interface _SERVICE {
  '_initialize_access_control' : ActorMethod<[], undefined>,
  '_internet_identity_sign_in_finish' : ActorMethod<[], Result__1>,
  '_internet_identity_sign_in_start' : ActorMethod<[], Uint8Array>,
  'addComment' : ActorMethod<[TabId, CommentInput], [] | [CommentView]>,
  'addReply' : ActorMethod<[CommentId, ReplyInput], [] | [CommentView]>,
  'addStroke' : ActorMethod<[TabId, StrokeInput], [] | [StrokeView]>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createRegion' : ActorMethod<
    [TabId, RegionInput],
    [] | [GeneratedRegionView]
  >,
  'createTab' : ActorMethod<[ProjectId, string], [] | [TabView]>,
  'deleteComment' : ActorMethod<[CommentId], [] | [boolean]>,
  'deleteRegion' : ActorMethod<[RegionId], [] | [boolean]>,
  'deleteStroke' : ActorMethod<[StrokeId], [] | [boolean]>,
  'deleteTab' : ActorMethod<[TabId], [] | [boolean]>,
  'execute' : ActorMethod<[string], Result>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getComments' : ActorMethod<[TabId], Array<CommentView>>,
  'getPresence' : ActorMethod<[], Array<PresenceView>>,
  'getProject' : ActorMethod<[], [] | [ProjectView]>,
  'getRegions' : ActorMethod<[TabId], Array<GeneratedRegionView>>,
  'getStrokes' : ActorMethod<[TabId], Array<StrokeView>>,
  'getTabs' : ActorMethod<[ProjectId], Array<TabView>>,
  'insertTemplate' : ActorMethod<
    [TabId, TemplateId, number, number, number, number],
    [] | [GeneratedRegionView]
  >,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listRegionVersions' : ActorMethod<[RegionId], Array<RegionVersionView>>,
  'listTemplates' : ActorMethod<[], Array<TemplateView>>,
  'regenerateRegion' : ActorMethod<
    [RegionId, string],
    [] | [GeneratedRegionView]
  >,
  'renameTab' : ActorMethod<[TabId, string], [] | [TabView]>,
  'reorderTabs' : ActorMethod<[ProjectId, Array<TabId>], Array<TabView>>,
  'restoreRegionVersion' : ActorMethod<
    [RegionId, bigint],
    [] | [GeneratedRegionView]
  >,
  'schema' : ActorMethod<[], string>,
  'searchTemplates' : ActorMethod<[string], Array<TemplateView>>,
  'undoLastStroke' : ActorMethod<[TabId], [] | [StrokeView]>,
  'updateProjectName' : ActorMethod<[string], [] | [ProjectView]>,
  'updateRegion' : ActorMethod<
    [RegionId, RegionUpdate],
    [] | [GeneratedRegionView]
  >,
  'upsertPresence' : ActorMethod<[PresenceInput], PresenceView>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];