/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.2.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Error = IDL.Variant({
  'FrontendOriginsNotConfigured' : IDL.Null,
  'MixedSsoSources' : IDL.Record({
    'otherKeys' : IDL.Vec(IDL.Text),
    'ssoKeys' : IDL.Vec(IDL.Text),
  }),
  'Stale' : IDL.Record({ 'ageNs' : IDL.Nat }),
  'MalformedCandid' : IDL.Null,
  'AmbiguousAttribute' : IDL.Record({
    'field' : IDL.Text,
    'sources' : IDL.Vec(IDL.Text),
  }),
  'NoAttributes' : IDL.Null,
  'UnknownNonce' : IDL.Null,
  'UntrustedSsoSource' : IDL.Record({ 'domain' : IDL.Text }),
  'MissingField' : IDL.Text,
  'FrontendOriginMismatch' : IDL.Record({
    'got' : IDL.Text,
    'expected' : IDL.Vec(IDL.Text),
  }),
});
export const Result__1 = IDL.Variant({ 'ok' : IDL.Null, 'err' : Error });
export const TabId = IDL.Nat;
export const CommentInput = IDL.Record({
  'x' : IDL.Float64,
  'y' : IDL.Float64,
  'text' : IDL.Text,
  'author' : IDL.Text,
});
export const CommentId = IDL.Nat;
export const Timestamp = IDL.Nat;
export const ReplyView = IDL.Record({
  'createdAt' : Timestamp,
  'text' : IDL.Text,
  'author' : IDL.Text,
});
export const CommentView = IDL.Record({
  'x' : IDL.Float64,
  'y' : IDL.Float64,
  'id' : CommentId,
  'tabId' : TabId,
  'createdAt' : Timestamp,
  'text' : IDL.Text,
  'author' : IDL.Text,
  'replies' : IDL.Vec(ReplyView),
});
export const ReplyInput = IDL.Record({
  'text' : IDL.Text,
  'author' : IDL.Text,
});
export const Tool = IDL.Variant({ 'pen' : IDL.Null, 'eraser' : IDL.Null });
export const Point = IDL.Record({ 'x' : IDL.Float64, 'y' : IDL.Float64 });
export const StrokeInput = IDL.Record({
  'color' : IDL.Text,
  'size' : IDL.Float64,
  'tool' : Tool,
  'points' : IDL.Vec(Point),
});
export const StrokeId = IDL.Nat;
export const StrokeView = IDL.Record({
  'id' : StrokeId,
  'tabId' : TabId,
  'createdAt' : Timestamp,
  'color' : IDL.Text,
  'size' : IDL.Float64,
  'tool' : Tool,
  'points' : IDL.Vec(Point),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const RegionInput = IDL.Record({
  'x' : IDL.Float64,
  'y' : IDL.Float64,
  'height' : IDL.Float64,
  'prompt' : IDL.Text,
  'width' : IDL.Float64,
});
export const RegionId = IDL.Nat;
export const RegionStatus = IDL.Variant({
  'pending' : IDL.Null,
  'done' : IDL.Null,
  'generating' : IDL.Null,
  'error' : IDL.Null,
});
export const GeneratedRegionView = IDL.Record({
  'x' : IDL.Float64,
  'y' : IDL.Float64,
  'id' : RegionId,
  'height' : IDL.Float64,
  'status' : RegionStatus,
  'tabId' : TabId,
  'createdAt' : Timestamp,
  'updatedAt' : Timestamp,
  'prompt' : IDL.Text,
  'width' : IDL.Float64,
  'generatedHtml' : IDL.Text,
});
export const ProjectId = IDL.Nat;
export const TabView = IDL.Record({
  'id' : TabId,
  'order' : IDL.Nat,
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'updatedAt' : Timestamp,
  'projectId' : ProjectId,
});
export const Value = IDL.Variant({
  'int' : IDL.Int,
  'nat' : IDL.Nat,
  'float' : IDL.Float64,
  'bool' : IDL.Bool,
  'null' : IDL.Null,
  'text' : IDL.Text,
});
export const Cell = IDL.Record({ 'value' : Value, 'name' : IDL.Text });
export const Result = IDL.Record({
  'hasMore' : IDL.Bool,
  'rows' : IDL.Vec(IDL.Vec(Cell)),
});
export const PrincipalText = IDL.Text;
export const PresenceView = IDL.Record({
  'principal' : PrincipalText,
  'displayName' : IDL.Text,
  'color' : IDL.Text,
  'activeTabId' : TabId,
  'cursorX' : IDL.Float64,
  'cursorY' : IDL.Float64,
  'lastSeen' : Timestamp,
  'activeTool' : IDL.Text,
});
export const ProjectView = IDL.Record({
  'id' : ProjectId,
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'updatedAt' : Timestamp,
});
export const TemplateId = IDL.Nat;
export const RegionVersionView = IDL.Record({
  'versionId' : IDL.Nat,
  'createdAt' : Timestamp,
  'prompt' : IDL.Text,
  'regionId' : RegionId,
  'generatedHtml' : IDL.Text,
});
export const TemplateView = IDL.Record({
  'id' : TemplateId,
  'html' : IDL.Text,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'category' : IDL.Text,
});
export const RegionUpdate = IDL.Record({
  'x' : IDL.Opt(IDL.Float64),
  'y' : IDL.Opt(IDL.Float64),
  'height' : IDL.Opt(IDL.Float64),
  'status' : IDL.Opt(RegionStatus),
  'prompt' : IDL.Opt(IDL.Text),
  'width' : IDL.Opt(IDL.Float64),
  'generatedHtml' : IDL.Opt(IDL.Text),
});
export const PresenceInput = IDL.Record({
  'displayName' : IDL.Text,
  'color' : IDL.Text,
  'activeTabId' : TabId,
  'cursorX' : IDL.Float64,
  'cursorY' : IDL.Float64,
  'activeTool' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initialize_access_control' : IDL.Func([], [], []),
  '_internet_identity_sign_in_finish' : IDL.Func([], [Result__1], []),
  '_internet_identity_sign_in_start' : IDL.Func([], [IDL.Vec(IDL.Nat8)], []),
  'addComment' : IDL.Func([TabId, CommentInput], [IDL.Opt(CommentView)], []),
  'addReply' : IDL.Func([CommentId, ReplyInput], [IDL.Opt(CommentView)], []),
  'addStroke' : IDL.Func([TabId, StrokeInput], [IDL.Opt(StrokeView)], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createRegion' : IDL.Func(
      [TabId, RegionInput],
      [IDL.Opt(GeneratedRegionView)],
      [],
    ),
  'createTab' : IDL.Func([ProjectId, IDL.Text], [IDL.Opt(TabView)], []),
  'deleteComment' : IDL.Func([CommentId], [IDL.Opt(IDL.Bool)], []),
  'deleteRegion' : IDL.Func([RegionId], [IDL.Opt(IDL.Bool)], []),
  'deleteStroke' : IDL.Func([StrokeId], [IDL.Opt(IDL.Bool)], []),
  'deleteTab' : IDL.Func([TabId], [IDL.Opt(IDL.Bool)], []),
  'execute' : IDL.Func([IDL.Text], [Result], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getComments' : IDL.Func([TabId], [IDL.Vec(CommentView)], ['query']),
  'getPresence' : IDL.Func([], [IDL.Vec(PresenceView)], ['query']),
  'getProject' : IDL.Func([], [IDL.Opt(ProjectView)], []),
  'getRegions' : IDL.Func([TabId], [IDL.Vec(GeneratedRegionView)], ['query']),
  'getStrokes' : IDL.Func([TabId], [IDL.Vec(StrokeView)], ['query']),
  'getTabs' : IDL.Func([ProjectId], [IDL.Vec(TabView)], ['query']),
  'insertTemplate' : IDL.Func(
      [TabId, TemplateId, IDL.Float64, IDL.Float64, IDL.Float64, IDL.Float64],
      [IDL.Opt(GeneratedRegionView)],
      [],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listRegionVersions' : IDL.Func(
      [RegionId],
      [IDL.Vec(RegionVersionView)],
      ['query'],
    ),
  'listTemplates' : IDL.Func([], [IDL.Vec(TemplateView)], ['query']),
  'regenerateRegion' : IDL.Func(
      [RegionId, IDL.Text],
      [IDL.Opt(GeneratedRegionView)],
      [],
    ),
  'renameTab' : IDL.Func([TabId, IDL.Text], [IDL.Opt(TabView)], []),
  'reorderTabs' : IDL.Func([ProjectId, IDL.Vec(TabId)], [IDL.Vec(TabView)], []),
  'restoreRegionVersion' : IDL.Func(
      [RegionId, IDL.Nat],
      [IDL.Opt(GeneratedRegionView)],
      [],
    ),
  'schema' : IDL.Func([], [IDL.Text], ['query']),
  'searchTemplates' : IDL.Func([IDL.Text], [IDL.Vec(TemplateView)], ['query']),
  'undoLastStroke' : IDL.Func([TabId], [IDL.Opt(StrokeView)], []),
  'updateProjectName' : IDL.Func([IDL.Text], [IDL.Opt(ProjectView)], []),
  'updateRegion' : IDL.Func(
      [RegionId, RegionUpdate],
      [IDL.Opt(GeneratedRegionView)],
      [],
    ),
  'upsertPresence' : IDL.Func([PresenceInput], [PresenceView], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Error = IDL.Variant({
    'FrontendOriginsNotConfigured' : IDL.Null,
    'MixedSsoSources' : IDL.Record({
      'otherKeys' : IDL.Vec(IDL.Text),
      'ssoKeys' : IDL.Vec(IDL.Text),
    }),
    'Stale' : IDL.Record({ 'ageNs' : IDL.Nat }),
    'MalformedCandid' : IDL.Null,
    'AmbiguousAttribute' : IDL.Record({
      'field' : IDL.Text,
      'sources' : IDL.Vec(IDL.Text),
    }),
    'NoAttributes' : IDL.Null,
    'UnknownNonce' : IDL.Null,
    'UntrustedSsoSource' : IDL.Record({ 'domain' : IDL.Text }),
    'MissingField' : IDL.Text,
    'FrontendOriginMismatch' : IDL.Record({
      'got' : IDL.Text,
      'expected' : IDL.Vec(IDL.Text),
    }),
  });
  const Result__1 = IDL.Variant({ 'ok' : IDL.Null, 'err' : Error });
  const TabId = IDL.Nat;
  const CommentInput = IDL.Record({
    'x' : IDL.Float64,
    'y' : IDL.Float64,
    'text' : IDL.Text,
    'author' : IDL.Text,
  });
  const CommentId = IDL.Nat;
  const Timestamp = IDL.Nat;
  const ReplyView = IDL.Record({
    'createdAt' : Timestamp,
    'text' : IDL.Text,
    'author' : IDL.Text,
  });
  const CommentView = IDL.Record({
    'x' : IDL.Float64,
    'y' : IDL.Float64,
    'id' : CommentId,
    'tabId' : TabId,
    'createdAt' : Timestamp,
    'text' : IDL.Text,
    'author' : IDL.Text,
    'replies' : IDL.Vec(ReplyView),
  });
  const ReplyInput = IDL.Record({ 'text' : IDL.Text, 'author' : IDL.Text });
  const Tool = IDL.Variant({ 'pen' : IDL.Null, 'eraser' : IDL.Null });
  const Point = IDL.Record({ 'x' : IDL.Float64, 'y' : IDL.Float64 });
  const StrokeInput = IDL.Record({
    'color' : IDL.Text,
    'size' : IDL.Float64,
    'tool' : Tool,
    'points' : IDL.Vec(Point),
  });
  const StrokeId = IDL.Nat;
  const StrokeView = IDL.Record({
    'id' : StrokeId,
    'tabId' : TabId,
    'createdAt' : Timestamp,
    'color' : IDL.Text,
    'size' : IDL.Float64,
    'tool' : Tool,
    'points' : IDL.Vec(Point),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const RegionInput = IDL.Record({
    'x' : IDL.Float64,
    'y' : IDL.Float64,
    'height' : IDL.Float64,
    'prompt' : IDL.Text,
    'width' : IDL.Float64,
  });
  const RegionId = IDL.Nat;
  const RegionStatus = IDL.Variant({
    'pending' : IDL.Null,
    'done' : IDL.Null,
    'generating' : IDL.Null,
    'error' : IDL.Null,
  });
  const GeneratedRegionView = IDL.Record({
    'x' : IDL.Float64,
    'y' : IDL.Float64,
    'id' : RegionId,
    'height' : IDL.Float64,
    'status' : RegionStatus,
    'tabId' : TabId,
    'createdAt' : Timestamp,
    'updatedAt' : Timestamp,
    'prompt' : IDL.Text,
    'width' : IDL.Float64,
    'generatedHtml' : IDL.Text,
  });
  const ProjectId = IDL.Nat;
  const TabView = IDL.Record({
    'id' : TabId,
    'order' : IDL.Nat,
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'updatedAt' : Timestamp,
    'projectId' : ProjectId,
  });
  const Value = IDL.Variant({
    'int' : IDL.Int,
    'nat' : IDL.Nat,
    'float' : IDL.Float64,
    'bool' : IDL.Bool,
    'null' : IDL.Null,
    'text' : IDL.Text,
  });
  const Cell = IDL.Record({ 'value' : Value, 'name' : IDL.Text });
  const Result = IDL.Record({
    'hasMore' : IDL.Bool,
    'rows' : IDL.Vec(IDL.Vec(Cell)),
  });
  const PrincipalText = IDL.Text;
  const PresenceView = IDL.Record({
    'principal' : PrincipalText,
    'displayName' : IDL.Text,
    'color' : IDL.Text,
    'activeTabId' : TabId,
    'cursorX' : IDL.Float64,
    'cursorY' : IDL.Float64,
    'lastSeen' : Timestamp,
    'activeTool' : IDL.Text,
  });
  const ProjectView = IDL.Record({
    'id' : ProjectId,
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'updatedAt' : Timestamp,
  });
  const TemplateId = IDL.Nat;
  const RegionVersionView = IDL.Record({
    'versionId' : IDL.Nat,
    'createdAt' : Timestamp,
    'prompt' : IDL.Text,
    'regionId' : RegionId,
    'generatedHtml' : IDL.Text,
  });
  const TemplateView = IDL.Record({
    'id' : TemplateId,
    'html' : IDL.Text,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'category' : IDL.Text,
  });
  const RegionUpdate = IDL.Record({
    'x' : IDL.Opt(IDL.Float64),
    'y' : IDL.Opt(IDL.Float64),
    'height' : IDL.Opt(IDL.Float64),
    'status' : IDL.Opt(RegionStatus),
    'prompt' : IDL.Opt(IDL.Text),
    'width' : IDL.Opt(IDL.Float64),
    'generatedHtml' : IDL.Opt(IDL.Text),
  });
  const PresenceInput = IDL.Record({
    'displayName' : IDL.Text,
    'color' : IDL.Text,
    'activeTabId' : TabId,
    'cursorX' : IDL.Float64,
    'cursorY' : IDL.Float64,
    'activeTool' : IDL.Text,
  });
  
  return IDL.Service({
    '_initialize_access_control' : IDL.Func([], [], []),
    '_internet_identity_sign_in_finish' : IDL.Func([], [Result__1], []),
    '_internet_identity_sign_in_start' : IDL.Func([], [IDL.Vec(IDL.Nat8)], []),
    'addComment' : IDL.Func([TabId, CommentInput], [IDL.Opt(CommentView)], []),
    'addReply' : IDL.Func([CommentId, ReplyInput], [IDL.Opt(CommentView)], []),
    'addStroke' : IDL.Func([TabId, StrokeInput], [IDL.Opt(StrokeView)], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createRegion' : IDL.Func(
        [TabId, RegionInput],
        [IDL.Opt(GeneratedRegionView)],
        [],
      ),
    'createTab' : IDL.Func([ProjectId, IDL.Text], [IDL.Opt(TabView)], []),
    'deleteComment' : IDL.Func([CommentId], [IDL.Opt(IDL.Bool)], []),
    'deleteRegion' : IDL.Func([RegionId], [IDL.Opt(IDL.Bool)], []),
    'deleteStroke' : IDL.Func([StrokeId], [IDL.Opt(IDL.Bool)], []),
    'deleteTab' : IDL.Func([TabId], [IDL.Opt(IDL.Bool)], []),
    'execute' : IDL.Func([IDL.Text], [Result], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getComments' : IDL.Func([TabId], [IDL.Vec(CommentView)], ['query']),
    'getPresence' : IDL.Func([], [IDL.Vec(PresenceView)], ['query']),
    'getProject' : IDL.Func([], [IDL.Opt(ProjectView)], []),
    'getRegions' : IDL.Func([TabId], [IDL.Vec(GeneratedRegionView)], ['query']),
    'getStrokes' : IDL.Func([TabId], [IDL.Vec(StrokeView)], ['query']),
    'getTabs' : IDL.Func([ProjectId], [IDL.Vec(TabView)], ['query']),
    'insertTemplate' : IDL.Func(
        [TabId, TemplateId, IDL.Float64, IDL.Float64, IDL.Float64, IDL.Float64],
        [IDL.Opt(GeneratedRegionView)],
        [],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listRegionVersions' : IDL.Func(
        [RegionId],
        [IDL.Vec(RegionVersionView)],
        ['query'],
      ),
    'listTemplates' : IDL.Func([], [IDL.Vec(TemplateView)], ['query']),
    'regenerateRegion' : IDL.Func(
        [RegionId, IDL.Text],
        [IDL.Opt(GeneratedRegionView)],
        [],
      ),
    'renameTab' : IDL.Func([TabId, IDL.Text], [IDL.Opt(TabView)], []),
    'reorderTabs' : IDL.Func(
        [ProjectId, IDL.Vec(TabId)],
        [IDL.Vec(TabView)],
        [],
      ),
    'restoreRegionVersion' : IDL.Func(
        [RegionId, IDL.Nat],
        [IDL.Opt(GeneratedRegionView)],
        [],
      ),
    'schema' : IDL.Func([], [IDL.Text], ['query']),
    'searchTemplates' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(TemplateView)],
        ['query'],
      ),
    'undoLastStroke' : IDL.Func([TabId], [IDL.Opt(StrokeView)], []),
    'updateProjectName' : IDL.Func([IDL.Text], [IDL.Opt(ProjectView)], []),
    'updateRegion' : IDL.Func(
        [RegionId, RegionUpdate],
        [IDL.Opt(GeneratedRegionView)],
        [],
      ),
    'upsertPresence' : IDL.Func([PresenceInput], [PresenceView], []),
  });
};

export const init = ({ IDL }) => { return []; };