/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.2.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
import { ExternalBlob } from "@caffeineai/object-storage";
export { ExternalBlob } from "@caffeineai/object-storage";
export type Timestamp = bigint;
export interface ReplyInput {
    text: string;
    author: string;
}
export interface Point {
    x: number;
    y: number;
}
export type TemplateId = bigint;
export type Result__1 = {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: Error_;
};
export interface ReplyView {
    createdAt: Timestamp;
    text: string;
    author: string;
}
export interface GeneratedRegionView {
    x: number;
    y: number;
    id: RegionId;
    height: number;
    status: RegionStatus;
    tabId: TabId;
    createdAt: Timestamp;
    updatedAt: Timestamp;
    prompt: string;
    width: number;
    generatedHtml: string;
}
export interface TemplateView {
    id: TemplateId;
    html: string;
    name: string;
    description: string;
    category: string;
}
export interface TabView {
    id: TabId;
    order: bigint;
    name: string;
    createdAt: Timestamp;
    updatedAt: Timestamp;
    projectId: ProjectId;
}
export interface RegionVersionView {
    versionId: bigint;
    createdAt: Timestamp;
    prompt: string;
    regionId: RegionId;
    generatedHtml: string;
}
export interface Cell {
    value: Value;
    name: string;
}
export interface PresenceInput {
    displayName: string;
    color: string;
    activeTabId: TabId;
    cursorX: number;
    cursorY: number;
    activeTool: string;
}
export type Value = {
    __kind__: "int";
    int: bigint;
} | {
    __kind__: "nat";
    nat: bigint;
} | {
    __kind__: "float";
    float: number;
} | {
    __kind__: "bool";
    bool: boolean;
} | {
    __kind__: "null";
    null: null;
} | {
    __kind__: "text";
    text: string;
};
export type PrincipalText = string;
export type StrokeId = bigint;
export interface RegionUpdate {
    x?: number;
    y?: number;
    height?: number;
    status?: RegionStatus;
    prompt?: string;
    width?: number;
    generatedHtml?: string;
}
export type CommentId = bigint;
export interface PresenceView {
    principal: PrincipalText;
    displayName: string;
    color: string;
    activeTabId: TabId;
    cursorX: number;
    cursorY: number;
    lastSeen: Timestamp;
    activeTool: string;
}
export interface ProjectView {
    id: ProjectId;
    name: string;
    createdAt: Timestamp;
    updatedAt: Timestamp;
}
export type Error_ = {
    __kind__: "FrontendOriginsNotConfigured";
    FrontendOriginsNotConfigured: null;
} | {
    __kind__: "MixedSsoSources";
    MixedSsoSources: {
        otherKeys: Array<string>;
        ssoKeys: Array<string>;
    };
} | {
    __kind__: "Stale";
    Stale: {
        ageNs: bigint;
    };
} | {
    __kind__: "MalformedCandid";
    MalformedCandid: null;
} | {
    __kind__: "AmbiguousAttribute";
    AmbiguousAttribute: {
        field: string;
        sources: Array<string>;
    };
} | {
    __kind__: "NoAttributes";
    NoAttributes: null;
} | {
    __kind__: "UnknownNonce";
    UnknownNonce: null;
} | {
    __kind__: "UntrustedSsoSource";
    UntrustedSsoSource: {
        domain: string;
    };
} | {
    __kind__: "MissingField";
    MissingField: string;
} | {
    __kind__: "FrontendOriginMismatch";
    FrontendOriginMismatch: {
        got: string;
        expected: Array<string>;
    };
};
export interface CommentView {
    x: number;
    y: number;
    id: CommentId;
    tabId: TabId;
    createdAt: Timestamp;
    text: string;
    author: string;
    replies: Array<ReplyView>;
}
export interface StrokeInput {
    color: string;
    size: number;
    tool: Tool;
    points: Array<Point>;
}
export interface Result {
    hasMore: boolean;
    rows: Array<Array<Cell>>;
}
export type RegionId = bigint;
export interface CommentInput {
    x: number;
    y: number;
    text: string;
    author: string;
}
export type ProjectId = bigint;
export type TabId = bigint;
export interface StrokeView {
    id: StrokeId;
    tabId: TabId;
    createdAt: Timestamp;
    color: string;
    size: number;
    tool: Tool;
    points: Array<Point>;
}
export interface RegionInput {
    x: number;
    y: number;
    height: number;
    prompt: string;
    width: number;
}
export enum RegionStatus {
    pending = "pending",
    done = "done",
    generating = "generating",
    error = "error"
}
export enum Tool {
    pen = "pen",
    eraser = "eraser"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initialize_access_control(): Promise<void>;
    _internet_identity_sign_in_finish(): Promise<Result__1>;
    _internet_identity_sign_in_start(): Promise<Uint8Array>;
    addComment(tabId: TabId, comment: CommentInput): Promise<CommentView | null>;
    addReply(commentId: CommentId, reply: ReplyInput): Promise<CommentView | null>;
    addStroke(tabId: TabId, stroke: StrokeInput): Promise<StrokeView | null>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createRegion(tabId: TabId, region: RegionInput): Promise<GeneratedRegionView | null>;
    createTab(projectId: ProjectId, name: string): Promise<TabView | null>;
    deleteComment(commentId: CommentId): Promise<boolean | null>;
    deleteRegion(regionId: RegionId): Promise<boolean | null>;
    deleteStroke(strokeId: StrokeId): Promise<boolean | null>;
    deleteTab(tabId: TabId): Promise<boolean | null>;
    execute(qJson: string): Promise<Result>;
    getCallerUserRole(): Promise<UserRole>;
    getComments(tabId: TabId): Promise<Array<CommentView>>;
    getPresence(): Promise<Array<PresenceView>>;
    getProject(): Promise<ProjectView | null>;
    getRegions(tabId: TabId): Promise<Array<GeneratedRegionView>>;
    getStrokes(tabId: TabId): Promise<Array<StrokeView>>;
    getTabs(projectId: ProjectId): Promise<Array<TabView>>;
    insertTemplate(tabId: TabId, templateId: TemplateId, x: number, y: number, width: number, height: number): Promise<GeneratedRegionView | null>;
    isCallerAdmin(): Promise<boolean>;
    listRegionVersions(regionId: RegionId): Promise<Array<RegionVersionView>>;
    listTemplates(): Promise<Array<TemplateView>>;
    regenerateRegion(regionId: RegionId, newPrompt: string): Promise<GeneratedRegionView | null>;
    renameTab(tabId: TabId, name: string): Promise<TabView | null>;
    reorderTabs(projectId: ProjectId, tabIds: Array<TabId>): Promise<Array<TabView>>;
    restoreRegionVersion(regionId: RegionId, versionId: bigint): Promise<GeneratedRegionView | null>;
    schema(): Promise<string>;
    searchTemplates(queryText: string): Promise<Array<TemplateView>>;
    undoLastStroke(tabId: TabId): Promise<StrokeView | null>;
    updateProjectName(name: string): Promise<ProjectView | null>;
    updateRegion(regionId: RegionId, updates: RegionUpdate): Promise<GeneratedRegionView | null>;
    upsertPresence(presence: PresenceInput): Promise<PresenceView>;
}
import type { Cell as _Cell, CommentView as _CommentView, Error as _Error, GeneratedRegionView as _GeneratedRegionView, Point as _Point, ProjectView as _ProjectView, RegionId as _RegionId, RegionStatus as _RegionStatus, RegionUpdate as _RegionUpdate, Result as _Result, Result__1 as _Result__1, StrokeId as _StrokeId, StrokeInput as _StrokeInput, StrokeView as _StrokeView, TabId as _TabId, TabView as _TabView, Timestamp as _Timestamp, Tool as _Tool, UserRole as _UserRole, Value as _Value } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initialize_access_control(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initialize_access_control();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initialize_access_control();
            return result;
        }
    }
    async _internet_identity_sign_in_finish(): Promise<Result__1> {
        if (this.processError) {
            try {
                const result = await this.actor._internet_identity_sign_in_finish();
                return from_candid_Result__1_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._internet_identity_sign_in_finish();
            return from_candid_Result__1_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async _internet_identity_sign_in_start(): Promise<Uint8Array> {
        if (this.processError) {
            try {
                const result = await this.actor._internet_identity_sign_in_start();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._internet_identity_sign_in_start();
            return result;
        }
    }
    async addComment(arg0: TabId, arg1: CommentInput): Promise<CommentView | null> {
        if (this.processError) {
            try {
                const result = await this.actor.addComment(arg0, arg1);
                return from_candid_opt_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addComment(arg0, arg1);
            return from_candid_opt_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async addReply(arg0: CommentId, arg1: ReplyInput): Promise<CommentView | null> {
        if (this.processError) {
            try {
                const result = await this.actor.addReply(arg0, arg1);
                return from_candid_opt_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addReply(arg0, arg1);
            return from_candid_opt_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async addStroke(arg0: TabId, arg1: StrokeInput): Promise<StrokeView | null> {
        if (this.processError) {
            try {
                const result = await this.actor.addStroke(arg0, to_candid_StrokeInput_n6(this._uploadFile, this._downloadFile, arg1));
                return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addStroke(arg0, to_candid_StrokeInput_n6(this._uploadFile, this._downloadFile, arg1));
            return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n15(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n15(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createRegion(arg0: TabId, arg1: RegionInput): Promise<GeneratedRegionView | null> {
        if (this.processError) {
            try {
                const result = await this.actor.createRegion(arg0, arg1);
                return from_candid_opt_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createRegion(arg0, arg1);
            return from_candid_opt_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async createTab(arg0: ProjectId, arg1: string): Promise<TabView | null> {
        if (this.processError) {
            try {
                const result = await this.actor.createTab(arg0, arg1);
                return from_candid_opt_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createTab(arg0, arg1);
            return from_candid_opt_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteComment(arg0: CommentId): Promise<boolean | null> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteComment(arg0);
                return from_candid_opt_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteComment(arg0);
            return from_candid_opt_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteRegion(arg0: RegionId): Promise<boolean | null> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteRegion(arg0);
                return from_candid_opt_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteRegion(arg0);
            return from_candid_opt_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteStroke(arg0: StrokeId): Promise<boolean | null> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteStroke(arg0);
                return from_candid_opt_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteStroke(arg0);
            return from_candid_opt_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteTab(arg0: TabId): Promise<boolean | null> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteTab(arg0);
                return from_candid_opt_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteTab(arg0);
            return from_candid_opt_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async execute(arg0: string): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.execute(arg0);
                return from_candid_Result_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.execute(arg0);
            return from_candid_Result_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n32(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n32(this._uploadFile, this._downloadFile, result);
        }
    }
    async getComments(arg0: TabId): Promise<Array<CommentView>> {
        if (this.processError) {
            try {
                const result = await this.actor.getComments(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getComments(arg0);
            return result;
        }
    }
    async getPresence(): Promise<Array<PresenceView>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPresence();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPresence();
            return result;
        }
    }
    async getProject(): Promise<ProjectView | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getProject();
                return from_candid_opt_n34(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProject();
            return from_candid_opt_n34(this._uploadFile, this._downloadFile, result);
        }
    }
    async getRegions(arg0: TabId): Promise<Array<GeneratedRegionView>> {
        if (this.processError) {
            try {
                const result = await this.actor.getRegions(arg0);
                return from_candid_vec_n35(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRegions(arg0);
            return from_candid_vec_n35(this._uploadFile, this._downloadFile, result);
        }
    }
    async getStrokes(arg0: TabId): Promise<Array<StrokeView>> {
        if (this.processError) {
            try {
                const result = await this.actor.getStrokes(arg0);
                return from_candid_vec_n36(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStrokes(arg0);
            return from_candid_vec_n36(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTabs(arg0: ProjectId): Promise<Array<TabView>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTabs(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTabs(arg0);
            return result;
        }
    }
    async insertTemplate(arg0: TabId, arg1: TemplateId, arg2: number, arg3: number, arg4: number, arg5: number): Promise<GeneratedRegionView | null> {
        if (this.processError) {
            try {
                const result = await this.actor.insertTemplate(arg0, arg1, arg2, arg3, arg4, arg5);
                return from_candid_opt_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.insertTemplate(arg0, arg1, arg2, arg3, arg4, arg5);
            return from_candid_opt_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async listRegionVersions(arg0: RegionId): Promise<Array<RegionVersionView>> {
        if (this.processError) {
            try {
                const result = await this.actor.listRegionVersions(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listRegionVersions(arg0);
            return result;
        }
    }
    async listTemplates(): Promise<Array<TemplateView>> {
        if (this.processError) {
            try {
                const result = await this.actor.listTemplates();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listTemplates();
            return result;
        }
    }
    async regenerateRegion(arg0: RegionId, arg1: string): Promise<GeneratedRegionView | null> {
        if (this.processError) {
            try {
                const result = await this.actor.regenerateRegion(arg0, arg1);
                return from_candid_opt_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.regenerateRegion(arg0, arg1);
            return from_candid_opt_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async renameTab(arg0: TabId, arg1: string): Promise<TabView | null> {
        if (this.processError) {
            try {
                const result = await this.actor.renameTab(arg0, arg1);
                return from_candid_opt_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.renameTab(arg0, arg1);
            return from_candid_opt_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async reorderTabs(arg0: ProjectId, arg1: Array<TabId>): Promise<Array<TabView>> {
        if (this.processError) {
            try {
                const result = await this.actor.reorderTabs(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.reorderTabs(arg0, arg1);
            return result;
        }
    }
    async restoreRegionVersion(arg0: RegionId, arg1: bigint): Promise<GeneratedRegionView | null> {
        if (this.processError) {
            try {
                const result = await this.actor.restoreRegionVersion(arg0, arg1);
                return from_candid_opt_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.restoreRegionVersion(arg0, arg1);
            return from_candid_opt_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async schema(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.schema();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.schema();
            return result;
        }
    }
    async searchTemplates(arg0: string): Promise<Array<TemplateView>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchTemplates(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchTemplates(arg0);
            return result;
        }
    }
    async undoLastStroke(arg0: TabId): Promise<StrokeView | null> {
        if (this.processError) {
            try {
                const result = await this.actor.undoLastStroke(arg0);
                return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.undoLastStroke(arg0);
            return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateProjectName(arg0: string): Promise<ProjectView | null> {
        if (this.processError) {
            try {
                const result = await this.actor.updateProjectName(arg0);
                return from_candid_opt_n34(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateProjectName(arg0);
            return from_candid_opt_n34(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateRegion(arg0: RegionId, arg1: RegionUpdate): Promise<GeneratedRegionView | null> {
        if (this.processError) {
            try {
                const result = await this.actor.updateRegion(arg0, to_candid_RegionUpdate_n37(this._uploadFile, this._downloadFile, arg1));
                return from_candid_opt_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateRegion(arg0, to_candid_RegionUpdate_n37(this._uploadFile, this._downloadFile, arg1));
            return from_candid_opt_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async upsertPresence(arg0: PresenceInput): Promise<PresenceView> {
        if (this.processError) {
            try {
                const result = await this.actor.upsertPresence(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.upsertPresence(arg0);
            return result;
        }
    }
}
function from_candid_Cell_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Cell): Cell {
    return from_candid_record_n29(_uploadFile, _downloadFile, value);
}
function from_candid_Error_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Error): Error_ {
    return from_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function from_candid_GeneratedRegionView_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _GeneratedRegionView): GeneratedRegionView {
    return from_candid_record_n19(_uploadFile, _downloadFile, value);
}
function from_candid_RegionStatus_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _RegionStatus): RegionStatus {
    return from_candid_variant_n21(_uploadFile, _downloadFile, value);
}
function from_candid_Result__1_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result__1): Result__1 {
    return from_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function from_candid_Result_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result): Result {
    return from_candid_record_n25(_uploadFile, _downloadFile, value);
}
function from_candid_StrokeView_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _StrokeView): StrokeView {
    return from_candid_record_n12(_uploadFile, _downloadFile, value);
}
function from_candid_Tool_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Tool): Tool {
    return from_candid_variant_n14(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n33(_uploadFile, _downloadFile, value);
}
function from_candid_Value_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Value): Value {
    return from_candid_variant_n31(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_StrokeView]): StrokeView | null {
    return value.length === 0 ? null : from_candid_StrokeView_n11(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_GeneratedRegionView]): GeneratedRegionView | null {
    return value.length === 0 ? null : from_candid_GeneratedRegionView_n18(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_TabView]): TabView | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ProjectView]): ProjectView | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_CommentView]): CommentView | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _StrokeId;
    tabId: _TabId;
    createdAt: _Timestamp;
    color: string;
    size: number;
    tool: _Tool;
    points: Array<_Point>;
}): {
    id: StrokeId;
    tabId: TabId;
    createdAt: Timestamp;
    color: string;
    size: number;
    tool: Tool;
    points: Array<Point>;
} {
    return {
        id: value.id,
        tabId: value.tabId,
        createdAt: value.createdAt,
        color: value.color,
        size: value.size,
        tool: from_candid_Tool_n13(_uploadFile, _downloadFile, value.tool),
        points: value.points
    };
}
function from_candid_record_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    x: number;
    y: number;
    id: _RegionId;
    height: number;
    status: _RegionStatus;
    tabId: _TabId;
    createdAt: _Timestamp;
    updatedAt: _Timestamp;
    prompt: string;
    width: number;
    generatedHtml: string;
}): {
    x: number;
    y: number;
    id: RegionId;
    height: number;
    status: RegionStatus;
    tabId: TabId;
    createdAt: Timestamp;
    updatedAt: Timestamp;
    prompt: string;
    width: number;
    generatedHtml: string;
} {
    return {
        x: value.x,
        y: value.y,
        id: value.id,
        height: value.height,
        status: from_candid_RegionStatus_n20(_uploadFile, _downloadFile, value.status),
        tabId: value.tabId,
        createdAt: value.createdAt,
        updatedAt: value.updatedAt,
        prompt: value.prompt,
        width: value.width,
        generatedHtml: value.generatedHtml
    };
}
function from_candid_record_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    hasMore: boolean;
    rows: Array<Array<_Cell>>;
}): {
    hasMore: boolean;
    rows: Array<Array<Cell>>;
} {
    return {
        hasMore: value.hasMore,
        rows: from_candid_vec_n26(_uploadFile, _downloadFile, value.rows)
    };
}
function from_candid_record_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    value: _Value;
    name: string;
}): {
    value: Value;
    name: string;
} {
    return {
        value: from_candid_Value_n30(_uploadFile, _downloadFile, value.value),
        name: value.name
    };
}
function from_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pen: null;
} | {
    eraser: null;
}): Tool {
    return "pen" in value ? Tool.pen : "eraser" in value ? Tool.eraser : value;
}
function from_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: null;
} | {
    err: _Error;
}): {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: Error_;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: from_candid_Error_n3(_uploadFile, _downloadFile, value.err)
    } : value;
}
function from_candid_variant_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    done: null;
} | {
    generating: null;
} | {
    error: null;
}): RegionStatus {
    return "pending" in value ? RegionStatus.pending : "done" in value ? RegionStatus.done : "generating" in value ? RegionStatus.generating : "error" in value ? RegionStatus.error : value;
}
function from_candid_variant_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    int: bigint;
} | {
    nat: bigint;
} | {
    float: number;
} | {
    bool: boolean;
} | {
    null: null;
} | {
    text: string;
}): {
    __kind__: "int";
    int: bigint;
} | {
    __kind__: "nat";
    nat: bigint;
} | {
    __kind__: "float";
    float: number;
} | {
    __kind__: "bool";
    bool: boolean;
} | {
    __kind__: "null";
    null: null;
} | {
    __kind__: "text";
    text: string;
} {
    return "int" in value ? {
        __kind__: "int",
        int: value.int
    } : "nat" in value ? {
        __kind__: "nat",
        nat: value.nat
    } : "float" in value ? {
        __kind__: "float",
        float: value.float
    } : "bool" in value ? {
        __kind__: "bool",
        bool: value.bool
    } : "null" in value ? {
        __kind__: "null",
        null: value.null
    } : "text" in value ? {
        __kind__: "text",
        text: value.text
    } : value;
}
function from_candid_variant_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    FrontendOriginsNotConfigured: null;
} | {
    MixedSsoSources: {
        otherKeys: Array<string>;
        ssoKeys: Array<string>;
    };
} | {
    Stale: {
        ageNs: bigint;
    };
} | {
    MalformedCandid: null;
} | {
    AmbiguousAttribute: {
        field: string;
        sources: Array<string>;
    };
} | {
    NoAttributes: null;
} | {
    UnknownNonce: null;
} | {
    UntrustedSsoSource: {
        domain: string;
    };
} | {
    MissingField: string;
} | {
    FrontendOriginMismatch: {
        got: string;
        expected: Array<string>;
    };
}): {
    __kind__: "FrontendOriginsNotConfigured";
    FrontendOriginsNotConfigured: null;
} | {
    __kind__: "MixedSsoSources";
    MixedSsoSources: {
        otherKeys: Array<string>;
        ssoKeys: Array<string>;
    };
} | {
    __kind__: "Stale";
    Stale: {
        ageNs: bigint;
    };
} | {
    __kind__: "MalformedCandid";
    MalformedCandid: null;
} | {
    __kind__: "AmbiguousAttribute";
    AmbiguousAttribute: {
        field: string;
        sources: Array<string>;
    };
} | {
    __kind__: "NoAttributes";
    NoAttributes: null;
} | {
    __kind__: "UnknownNonce";
    UnknownNonce: null;
} | {
    __kind__: "UntrustedSsoSource";
    UntrustedSsoSource: {
        domain: string;
    };
} | {
    __kind__: "MissingField";
    MissingField: string;
} | {
    __kind__: "FrontendOriginMismatch";
    FrontendOriginMismatch: {
        got: string;
        expected: Array<string>;
    };
} {
    return "FrontendOriginsNotConfigured" in value ? {
        __kind__: "FrontendOriginsNotConfigured",
        FrontendOriginsNotConfigured: value.FrontendOriginsNotConfigured
    } : "MixedSsoSources" in value ? {
        __kind__: "MixedSsoSources",
        MixedSsoSources: value.MixedSsoSources
    } : "Stale" in value ? {
        __kind__: "Stale",
        Stale: value.Stale
    } : "MalformedCandid" in value ? {
        __kind__: "MalformedCandid",
        MalformedCandid: value.MalformedCandid
    } : "AmbiguousAttribute" in value ? {
        __kind__: "AmbiguousAttribute",
        AmbiguousAttribute: value.AmbiguousAttribute
    } : "NoAttributes" in value ? {
        __kind__: "NoAttributes",
        NoAttributes: value.NoAttributes
    } : "UnknownNonce" in value ? {
        __kind__: "UnknownNonce",
        UnknownNonce: value.UnknownNonce
    } : "UntrustedSsoSource" in value ? {
        __kind__: "UntrustedSsoSource",
        UntrustedSsoSource: value.UntrustedSsoSource
    } : "MissingField" in value ? {
        __kind__: "MissingField",
        MissingField: value.MissingField
    } : "FrontendOriginMismatch" in value ? {
        __kind__: "FrontendOriginMismatch",
        FrontendOriginMismatch: value.FrontendOriginMismatch
    } : value;
}
function from_candid_vec_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<Array<_Cell>>): Array<Array<Cell>> {
    return value.map((x)=>from_candid_vec_n27(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Cell>): Array<Cell> {
    return value.map((x)=>from_candid_Cell_n28(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_GeneratedRegionView>): Array<GeneratedRegionView> {
    return value.map((x)=>from_candid_GeneratedRegionView_n18(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_StrokeView>): Array<StrokeView> {
    return value.map((x)=>from_candid_StrokeView_n11(_uploadFile, _downloadFile, x));
}
function to_candid_RegionStatus_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: RegionStatus): _RegionStatus {
    return to_candid_variant_n40(_uploadFile, _downloadFile, value);
}
function to_candid_RegionUpdate_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: RegionUpdate): _RegionUpdate {
    return to_candid_record_n38(_uploadFile, _downloadFile, value);
}
function to_candid_StrokeInput_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: StrokeInput): _StrokeInput {
    return to_candid_record_n7(_uploadFile, _downloadFile, value);
}
function to_candid_Tool_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Tool): _Tool {
    return to_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n16(_uploadFile, _downloadFile, value);
}
function to_candid_record_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    x?: number;
    y?: number;
    height?: number;
    status?: RegionStatus;
    prompt?: string;
    width?: number;
    generatedHtml?: string;
}): {
    x: [] | [number];
    y: [] | [number];
    height: [] | [number];
    status: [] | [_RegionStatus];
    prompt: [] | [string];
    width: [] | [number];
    generatedHtml: [] | [string];
} {
    return {
        x: value.x ? candid_some(value.x) : candid_none(),
        y: value.y ? candid_some(value.y) : candid_none(),
        height: value.height ? candid_some(value.height) : candid_none(),
        status: value.status ? candid_some(to_candid_RegionStatus_n39(_uploadFile, _downloadFile, value.status)) : candid_none(),
        prompt: value.prompt ? candid_some(value.prompt) : candid_none(),
        width: value.width ? candid_some(value.width) : candid_none(),
        generatedHtml: value.generatedHtml ? candid_some(value.generatedHtml) : candid_none()
    };
}
function to_candid_record_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    color: string;
    size: number;
    tool: Tool;
    points: Array<Point>;
}): {
    color: string;
    size: number;
    tool: _Tool;
    points: Array<_Point>;
} {
    return {
        color: value.color,
        size: value.size,
        tool: to_candid_Tool_n8(_uploadFile, _downloadFile, value.tool),
        points: value.points
    };
}
function to_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: RegionStatus): {
    pending: null;
} | {
    done: null;
} | {
    generating: null;
} | {
    error: null;
} {
    return value == RegionStatus.pending ? {
        pending: null
    } : value == RegionStatus.done ? {
        done: null
    } : value == RegionStatus.generating ? {
        generating: null
    } : value == RegionStatus.error ? {
        error: null
    } : value;
}
function to_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Tool): {
    pen: null;
} | {
    eraser: null;
} {
    return value == Tool.pen ? {
        pen: null
    } : value == Tool.eraser ? {
        eraser: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
